spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/auth_db
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: admin

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  lifetime:
    access: 600 # 10 минут
    refresh: 1209600 # 14 дней
  secret: dmVyeVZlcnlTZWNyZXRLZXlGb3JKV1RBdXRoZW50aWNhdGlvbkluV2FsbGV0QXBwbGljYXRpb24=
  redis:
    keys:
      refresh: refresh:{userId}:{jti}
      blacklist: blacklist:{jti}