version: "3.9"

services:
  user-service-db:
    image: postgres:17.4-alpine3.21
    container_name: users_db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"