version: "3.9"

services:
  auth-service-db:
    image: postgres:17.4-alpine3.21
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"