server:
  port: 8081

uri:
  auth-service: http://localhost:8082
  verify-token: ${uri.auth-service}/api/v1/auth/verify
  operation-service: http://localhost:8083

headers:
  user-id: Wallet-User-Id

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: Auth service
              uri: ${uri.auth-service}
              predicates:
                - Path=/api/v1/auth/**

            - id: Operation service
              uri: ${uri.operation-service}
              predicates:
                - Path=/api/v1/operations/**
              filters:
                - PreAuth