server:
  port: 8081

uri:
  auth-service: http://localhost:8082

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: Registration
              uri: ${uri.auth-service}
              predicates:
                - Path=/api/v1/auth/**