spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/users_db
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none